### ISSUE TITLE
麻烦问下ios如何获取大头针title的frame呢?

### ISSUE THREAD

**Issue by slidoooor** [apicloudcom/aMap#3]
MAShape或者MAPointAnnotation或者MAAnnotation都没有frame相关暴露出来,应该怎么弄才能获取到呢,要根据起始点和出发点和中间的路径缩放地图,title的frame也要包含在计算内

**Comment by APICloud-com** [comment]
技术我呢提社区求助，有技术和版主给你回答



yunying@apicloud.com
 
发件人： Hans
发送时间： 2017-11-23 16:28
收件人： apicloudcom/aMap
抄送： Subscribed
主题： [apicloudcom/aMap] 麻烦问下ios如何获取大头针title的frame呢? (#3)
MAShape或者MAPointAnnotation或者MAAnnotation都没有frame相关暴露出来,应该怎么弄才能获取到呢,要根据起始点和出发点和中间的路径缩放地图,title的frame也要包含在计算内
―
