### ISSUE TITLE
自定义模块的名字不能修改为其他名字吗？只能是aMap?

### ISSUE THREAD

**Issue by ghit700** [apicloudcom/aMap#4]
我修改名字之后，在config里面设置了android_api_key，可是依旧会报高德地图1002这个验证失败，可是我用amap这个名字就不会，请问要在哪里修改这个设置？

**Comment by sunzhengcuan** [comment]
模块名需要和模块zip包module.json文件内的name一致即可。
有不清楚的可以看下模块开发的相关视频：http://www.apicloud.com/video_list
